apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend-service
    app: frontend-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    name: frontend-pod
    app: frontend-app
---

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: frontend-service
#  labels:
#    app: frontendApp
#    name: frontend-service
#spec:
#  type: NodePort
#  ports:
#    - targetPort: 3000
#      port: 3000
#      nodePort: 30008
#  selector:
#    app: myFrontend
#    type: front-end
#---
#
